config:
  APP_ENV: release
  AUTO_CREATE_TABLES: 'false'
  API_CORS_ORIGINS: http://10.34.200.180
  CELERY_NAMESPACE: hr-certflow-release
  CELERY_QUEUE: hr-certflow-release
  CELERY_ROUTING_KEY: hr-certflow-release
  CELERY_REDIS_HASH_TAG: hr-certflow-release
  CELERY_REDIS_PREFIX: 'hr-certflow-release:'
  S3_BUCKET: hr-certflow-release
images:
  api:
    repository: ghcr.io/jaredshuai/hr-certflow-api
    tag: e0054d5
  web:
    repository: ghcr.io/jaredshuai/hr-certflow-web
    tag: e0054d5
ingress:
  pathPrefix: /hr-certflow
api:
  replicas: 2
web:
  replicas: 2
worker:
  replicas: 1
beat:
  replicas: 1