config:
  APP_ENV: dev
  AUTO_CREATE_TABLES: 'false'
  API_CORS_ORIGINS: http://10.34.200.180
  CELERY_NAMESPACE: hr-certflow-dev
  CELERY_QUEUE: hr-certflow-dev
  CELERY_ROUTING_KEY: hr-certflow-dev
  CELERY_REDIS_HASH_TAG: hr-certflow-dev
  CELERY_REDIS_PREFIX: 'hr-certflow-dev:'
  S3_ENDPOINT_URL: https://oss-cn-hangzhou.aliyuncs.com
  S3_REGION: cn-hangzhou
  S3_BUCKET: jxccs-shared-infra-oss-cn-hangzhou
  S3_FORCE_PATH_STYLE: 'false'
  AWS_REQUEST_CHECKSUM_CALCULATION: when_required
  AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
  UPLOAD_PREFIX: hr-certflow/dev/certificates
images:
  api:
    repository: ghcr.io/jaredshuai/hr-certflow-api
    tag: c604fb5
  web:
    repository: ghcr.io/jaredshuai/hr-certflow-web
    tag: c604fb5
ingress:
  pathPrefix: /hr-certflow-dev
api:
  replicas: 1
web:
  replicas: 1
worker:
  replicas: 1
beat:
  replicas: 1
