config:
  APP_ENV: dev
  AUTO_CREATE_TABLES: 'false'
  API_CORS_ORIGINS: http://10.34.200.180
  CELERY_NAMESPACE: hr-certflow-dev
  CELERY_QUEUE: hr-certflow-dev
  CELERY_ROUTING_KEY: hr-certflow-dev
  CELERY_REDIS_HASH_TAG: hr-certflow-dev
  CELERY_REDIS_PREFIX: 'hr-certflow-dev:'
  S3_BUCKET: hr-certflow-dev
images:
  api:
    repository: ghcr.io/jaredshuai/hr-certflow-api
    tag: 2d7e19b
  web:
    repository: ghcr.io/jaredshuai/hr-certflow-web
    tag: 2d7e19b
ingress:
  pathPrefix: /hr-certflow
api:
  replicas: 1
web:
  replicas: 1
worker:
  replicas: 1
beat:
  replicas: 1
